/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";
import { useFrame } from "@react-three/fiber";

export function Bark({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/bark/model.glb");
  
  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1045108175.geometry}
        material={materials.mat20}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat20.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1045108175_1.geometry}
        material={materials.mat18}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat18.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1045108175_2.geometry}
        material={materials.mat16}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat16.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh1045108175_3.geometry}
        material={materials.mat15}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat15.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/bark/model.glb");
