/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";
import { useFrame } from "@react-three/fiber";

export function Daisy({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/daisy/model.glb");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null} rotation={[90,0,0]}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Daisys_Circle003-Mesh"].geometry}
        material={materials.Green_Daisy}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.Green_Daisy.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Daisys_Circle003-Mesh_1"].geometry}
        material={materials.Yellow_Daisy}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.Yellow_Daisy.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Daisys_Circle003-Mesh_2"].geometry}
        material={materials.White_Daisy}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.White_Daisy.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/daisy/model.glb");
