/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";
import { useFrame } from "@react-three/fiber";

export function Stone({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/stone/model.glb");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1988159041.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group337471551.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group765248285.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group697255115.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group821822121.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1383753236.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group1230782801.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.group295268605.geometry}
        material={materials.mat22}
      >
        <meshStandardMaterial
          ref={materialRef}
          color={materials.mat22.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/stone/model.glb");
