/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React, { useRef } from "react";
import { fadeOnBeforeCompile } from "../utils/fadeMaterial";
import { useFrame } from "@react-three/fiber";

export function Tree({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/tree/model.glb");

  const materialRef = useRef();

  useFrame(() => {
    materialRef.current.opacity = sceneOpacity.current;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh'].geometry}
        material={materials.mat9}
      >
       <meshStandardMaterial
          ref={materialRef}
          color={materials.mat9.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        /> </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.mat20}
      >
       <meshStandardMaterial
          ref={materialRef}
          color={materials.mat20.color}
          onBeforeCompile={fadeOnBeforeCompile}
          envMapIntensity={2}
          transparent
        /> </mesh>
    </group>
  );
}

useGLTF.preload("./models/tree/model.glb");
